filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run --standard=phpcs.xml.dist src/ tests/
          - command: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
