language: php

# php compatibility
php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"

matrix:
  allow_failures:
    - php: "7.4snapshot"

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer upgrade --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/php-cs-fixer fix --dry-run --verbose
  - vendor/bin/phpcs --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose
  - vendor/bin/phpstan analyse --no-progress --level max src/ tests/

notifications:
  email: false
